spring.application.name=backend


server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/TatingDatabase
spring.datasource.username=postgres
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SMS Gateway Configuration (Semaphore)
sms.mock-mode=false
sms.semaphore.api-key=${SEMAPHORE_API_KEY:}
sms.semaphore.sender-name=SEMAPHORE
sms.semaphore.api-url=https://api.semaphore.co/api/v4/messages
